name: Slow Magic Weddings
favicon: null
layout_spectrum: 0.7367042731493711
typography_spectrum: 0.6591537140775472
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8381950298789889
  lightness: 0.25682717422023416
  saturation: 0.1179787905421108
  rhythmicContrast: 0.6588175874203444
purpose: []
